### ISSUE TITLE
Portal proposes to copy and use a bad command (not complete) to receive.

### ISSUE THREAD

**Issue by ludetie** [SpatiumPortae/portal#46]
Hello,

I run the portal server and when i connect to it to send a file, "Portal" offers me to copy and to use a bad command line to receive the file:
![image](https://user-images.githubusercontent.com/91374123/220659863-45433148-8258-4b51-b319-a9a2596fc0e8.png)

instead of portal receive -a xxxxxxx -p xxxxxx code .

Regards,

**Comment by ZinoKader** [comment]
Hello, and thank you for your suggestion. This behavior is something me and @mellonnen discussed before and we weren't quite sure how users would like this to work. If you set the default values for relay address and port in .portal.yml in your home folder, you can issue the command without any extra flags.

I realize that it's probably more user-friendly to attach the address and port flags to the copy-command, though. Will look into it!

Thanks for your suggestion!

**Comment by ludetie** [comment]
Hello,

The .portal.yml is not taken into account, neither with domain name, nor with IP, even with nothing in it, the server is 167.71.65.96:80
I did not move the file.
I checked on ubuntu and windows, the issue is the same.
But it's working with -a and -p flags.

Regards,

**Comment by ZinoKader** [comment]
> Hello,
> 
> The .portal.yml is not taken into account, neither with domain name, nor with IP, even with nothing in it, the server is 167.71.65.96:80 I did not move the file. I checked on ubuntu and windows, the issue is the same. But it's working with -a and -p flags.
> 
> Regards,

It turns out that the config file has been broken for some time now. It has been fixed in #53, so you can now setup your relay server information there, so that you don't need to write it out in the flag every time! :)

Furthermore, if you are not using the default relay, the `--relay` flag (replaces `-a` and `-p`) will now be included in the copy command on the sender side.

The changes will be included in the next release which is coming up shortly.

Thank you very much @ludetie for this issue!
